# Generated by Django 4.2 on 2023-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFree',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('telegram_username', models.CharField(max_length=200)),
                ('sum_bought', models.IntegerField()),
            ],
        ),
    ]
