# Generated by Django 4.2 on 2023-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('subcategory', models.IntegerField()),
                ('pic_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
    ]
