# Generated by Django 4.2 on 2023-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='pic_id',
            field=models.CharField(),
        ),
    ]
