# Generated by Django 4.2 on 2023-04-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_alter_thing_pic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_api.thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_api.userfree')),
            ],
        ),
    ]
