# Generated by Django 4.2 on 2023-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_cartobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
